from .utils import bits_to_words

RADIX_BITS = 10

RADIX = 2 ** RADIX_BITS

ID_LENGTH_BITS = 15

ITERATION_EXP_LENGTH_BITS = 5

ID_EXP_LENGTH_WORDS = bits_to_words(ID_LENGTH_BITS + ITERATION_EXP_LENGTH_BITS)

MAX_SHARE_COUNT = 16

CHECKSUM_LENGTH_WORDS = 3

DIGEST_LENGTH_BYTES = 4

CUSTOMIZATION_STRING = b"shamir"

GROUP_PREFIX_LENGTH_WORDS = ID_EXP_LENGTH_WORDS + 1

METADATA_LENGTH_WORDS = ID_EXP_LENGTH_WORDS + 2 + CHECKSUM_LENGTH_WORDS

MIN_STRENGTH_BITS = 128

MIN_MNEMONIC_LENGTH_WORDS = METADATA_LENGTH_WORDS + bits_to_words(MIN_STRENGTH_BITS)

BASE_ITERATION_COUNT = 10_000

ROUND_COUNT = 4

SECRET_INDEX = 255

DIGEST_INDEX = 254
